version: '3'
services:
  redis-cluster:
    platform: linux/x86_64
    image: redis:6.2
    container_name: redis-cluster
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
      - 6380:6380
      - 6381:6381

  redis-node-1:
    network_mode: 'service:redis-cluster'
    platform: linux/x86_64
    image: redis:6.2
    container_name: redis-node1
    volumes:
      - ./redis1.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node-2:
    network_mode: 'service:redis-cluster'
    platform: linux/x86_64
    image: redis:6.2
    container_name: redis-node2
    volumes:
      - ./redis2.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-cluster-command:
    network_mode: 'service:redis-cluster'
    platform: linux/x86_64
    image: redis:6.2
    container_name: redis-cluster-command
    depends_on:
      - redis-cluster
      - redis-node-1
      - redis-node-2
    command: >
      sh -c "
        sleep 5 &&
        redis-cli -p 6379 flushall &&
        redis-cli -p 6379 cluster reset hard &&
        redis-cli -p 6380 flushall &&
        redis-cli -p 6380 cluster reset hard &&
        redis-cli -p 6381 flushall &&
        redis-cli -p 6381 cluster reset hard &&
        redis-cli --cluster create 127.0.0.1:6379 127.0.0.1:6380 127.0.0.1:6381 --cluster-yes &&
        echo 'success redis-cluster' &&
        exit 0
      "
    stop_signal: SIGINT
